import { getSupabaseServerClient } from "@/lib/supabaseClient";
import bcrypt from "bcryptjs";
import { NextRequest } from 'next/server';

export async function POST(req: NextRequest) {
  const { name, email, password, invite_token } = await req.json();

  try {
    const supabase = getSupabaseServerClient();
    let groupInvitation = null;
    let groupId = null;

    // If invite_token is provided, validate the invitation
    if (invite_token) {
      // Look up invitation by short_code first, then try invite_token
      let invitation: any = null;
      let invitationError: any = null;

      // Try short_code first
      let result = await supabase
        .from('group_invitations')
        .select('*')
        .eq('short_code', invite_token)
        .single();

      if (result.data) {
        invitation = result.data;
      } else {
        // If not found by short_code, try invite_token
        result = await supabase
          .from('group_invitations')
          .select('*')
          .eq('invite_token', invite_token)
          .single();
        
        invitation = result.data;
        invitationError = result.error;
      }

      if (invitationError || !invitation) {
        return new Response(
          JSON.stringify({ error: 'Invalid invitation token' }),
          { status: 400 }
        );
      }

      // Validate email matches invitation email
      if (invitation.email.toLowerCase() !== email.toLowerCase()) {
        return new Response(
          JSON.stringify({ error: 'Email does not match the invitation' }),
          { status: 400 }
        );
      }

      // Check expiration
      const expiresAt = new Date(invitation.expires_at);
      if (new Date() > expiresAt) {
        // Mark as expired
        await supabase
          .from('group_invitations')
          .update({ status: 'expired' })
          .eq('id', invitation.id);

        return new Response(
          JSON.stringify({ error: 'Invitation has expired' }),
          { status: 400 }
        );
      }

      // Check if already accepted
      if (invitation.status === 'accepted') {
        return new Response(
          JSON.stringify({ error: 'Invitation has already been accepted' }),
          { status: 400 }
        );
      }

      groupInvitation = invitation;
      groupId = invitation.group_id;
    }

    // Hash the password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Prepare user data matching our table schema
    const userData = {
      email,
      hashed_password: hashedPassword,
      name,
      role: "user"
      // created_at will be set by default in the database
      // id will be generated by gen_random_uuid() in the database
    };

    // Add the user to Supabase
    const { data, error } = await supabase
      .from("users")
      .insert([userData])
      .select(); // Add select to get back the created user data

    if (error) {
      return new Response(
        JSON.stringify({
          error: error.code === '23505' ? 'Email already exists' : error.message
        }),
        { status: error.code === '23505' ? 409 : 400 }
      );
    }

    const newUser = data[0];

    // If this was a group invitation, add user to the group
    if (groupInvitation && groupId) {
      // Add user as a member of the group
      const { error: memberError } = await supabase
        .from('group_members')
        .insert({
          user_id: newUser.id,
          group_id: groupId,
          role: 'Member',
          is_active: true,
        });

      if (memberError) {
        // User is created, but group membership failed - still return success
        // but log the error for manual fix if needed
      } else {
        // Mark invitation as accepted
        await supabase
          .from('group_invitations')
          .update({
            status: 'accepted',
            accepted_at: new Date().toISOString(),
          })
          .eq('id', groupInvitation.id);
      }
    }

    const response: any = { data };

    // If group invitation, include group info in response
    if (groupInvitation && groupId) {
      response.group_id = groupId;
      response.group_name = groupInvitation.group_name;
    }

    return new Response(JSON.stringify(response), { status: 201 });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: "An unexpected error occurred during registration." }),
      { status: 500 }
    );
  }
}